##--------------------------------------redis»º´æÅäÖÃ¿ªÊ¼---------------------------------------------------------
spring.redis.cluster.nodes=
##ÃÜÂë
spring.redis.password=
##--------------------------------------redis»º´æÅäÖÃ½áÊø---------------------------------------------------------