stages:
  - compile
  - test

compile:
  stage: compile
  script:
    mvn clean compile  -Dos.detected.name=linux -Dos.detected.arch=x86_64 -Dos.detected.classifier=linux-x86_64
  #mvn clean compile -Dos.detected.name=windows -Dos.detected.arch=x86_64 -Dos.detected.classifier=windows-x86_64
