
##-----------------------------------kafka server 开始------------------------------
#127.0.0.1:9092，多个逗号间隔
kafka.server.bootstrapServers=
kafka.server.requestTimeoutMs=30000

##////producer
#确认
kafka.producer.acks=all
#重试次数
kafka.producer.retries=3
#批次大小
kafka.producer.batchSize=16384
#等待时长，毫秒
kafka.producer.lingerMs=100
#RecordAccumulator 缓冲区大小
kafka.producer.bufferMemory=33554432
#key序列化
kafka.producer.keySerializer=org.apache.kafka.common.serialization.StringSerializer
#value序列化
kafka.producer.valueSerializer=org.apache.kafka.common.serialization.StringSerializer

##////consumer
#分组id
kafka.consumer.groupId=test
#是否开启自动提交
kafka.consumer.enableAutoCommit=false
#自动提交时间间隔，单位毫秒
kafka.consumer.autoCommitIntervalMs=10000
#key序列化
kafka.consumer.keySerializer=org.apache.kafka.common.serialization.StringSerializer
#value序列化
kafka.consumer.valueSerializer=org.apache.kafka.common.serialization.StringSerializer
##-----------------------------------kafka server 结束------------------------------