#spring:
#  elasticsearch:
#    rest:
#      uris: http://192.168.72.143:9200


apm:
  elasticsearch:
    rest:
      default:
        #http://127.0.0.1:9200，多个之间逗号间隔
        uris:
      source:
        uris: http://192.168.72.143:9200
      targest:
        uris: http://192.168.72.143:9200

server:
  port: 19000
