syntax = "proto3";

import "google/protobuf/wrappers.proto";

option java_multiple_files = true;
option java_package = "code.traveler.test.space.java.sb.grpc.lib.pilot";
option java_outer_classname = "PilotProto";
option go_package = "/v1";

package v1;

message PPilotPing {
}

message PPilotRequest {
  int32 requestId = 1;

  oneof message {
    // 心跳
    PPilotPing ping = 2;
    // pilot信息
    PPilotInfo pilotInfo = 3;
  }
}

message PPilotResponse {
  int32 responseId = 1;

  oneof message {
    PPilotPing ping = 2;
    PPilotConfigMessage pilotConfig = 3;
  }
}

message PPilotInfo {
  string pilotId = 1;
  string pilotInstanceId = 2;
  int64 startTime = 3;
  string version = 4;
  string pilotImageVersion = 5;
  string agentVersion = 6;
  repeated string nodeIps = 7;
}

message PPilotConfigMessage {
  string pilotId = 1;
  string pilotInstanceId = 2;
  string version = 3;

  string pilotImageVersion = 4;
  string pilotImageTag = 5;
  string pilotImageUrl = 6;

  string agentVersion = 7;
  string agentImageTag = 8;
  string agentImageUrl = 9;

  repeated PPilotFeatureConfig featureConfigs = 10;
}

message PPilotFeatureConfig {
  string agentId = 1;
  string applicationName = 2;
  string agentVersion = 3;
  string agentImageTag = 4;
  string agentImageUrl = 5;
}

service PilotService {
    rpc HandlePilot(stream PPilotRequest) returns (stream PPilotResponse) {
    }
}
