server:
  port: 80

demo:
  nacos:
    #nacosIp
    ip: 10.253.171.126
    #nacosPort
    port: 30266
    #nacosUsername
    username: nacos
    #kunluneye agent nacos password，测试为R00t@996
    password: 2z2rk!nn
    #kunluneye agent nacos namespace
    namespace: public
    #kunluneye agent nacos group
    group: DEFAULT_GROUP