server:
  port: 18999

jasypt:
  encryptor:
    password: "Y118&#5b"
    algorithm: PBEWithHMACSHA512AndAES_128
    #使用PBEWithMD5AndDES这个加密算法，2.1.1版本不用添加也可以，3.0.5不加会报错
    #iv-generator-classname: org.jasypt.iv.NoIvGenerator

#test:
#  password: ENC(p3+uVadW7On8kD6DNLTErqj980RlKHGNt4PHED+auqLKH3vu9qZXsr97l9Isp2XO)