<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>spring-boot-grpc-demo</artifactId>
        <groupId>code.traveler</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sb-grpc-lib</artifactId>

    <properties>
        <grpc.version>1.46.0</grpc.version>
        <protoc.version>3.20.1</protoc.version>
        <netty4.version>4.1.58.Final</netty4.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
            <version>1.46.0</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>code.traveler</groupId>-->
<!--            <artifactId>grpc-client-spring-boot-starter</artifactId>-->
<!--            <version>1.0.0</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>io.grpc</groupId>-->
<!--                    <artifactId>grpc-netty-shaded</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>code.traveler</groupId>-->
<!--            <artifactId>grpc-server-spring-boot-starter</artifactId>-->
<!--            <version>1.0.0</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>io.grpc</groupId>-->
<!--                    <artifactId>grpc-netty-shaded</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http2</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>${netty4.version}</version>
        </dependency>
        <dependency>
            <!-- https://netty.io/wiki/native-transports.html -->
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>${netty4.version}</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <protoSourceRoot>${basedir}/src/main/protobuf</protoSourceRoot>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>