server:
  port: 8888
spring:
  application:
    name: spring-boot-support-client

grpc:
  client:
    spring-boot-grpc-service:
      address: 'static://127.0.0.1:19999'
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true

    spring-boot-grpc-student-service:
      address: 'static://127.0.0.1:19999'
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true